"""Date de antrenament pentru intent classifier.

Trei clase (conform temei `hw8.pdf`):
  - search    : găsește / caută / arată documente sau informații
  - extract   : extrage date structurate (sume, date, TVA, părți, IBAN, ...)
  - summarize : rezumă / sintetizează / overview

Limbă mixtă RO + EN, domeniul facturi/contracte (ca restul proiectului).
💡 Generezi 50-100 exemple/clasă o singură dată, apoi antrenezi classifier-ul.

`TRAINING_DATA` = exemplele de antrenament; `TEST_DATA` = set held-out, formulări
distincte, folosit de `benchmark_intent.py` ca să compare onest LLM vs sklearn.
"""

LABELS = ["search", "extract", "summarize"]


TRAINING_DATA: list[tuple[str, str]] = [
    # ─────────────── SEARCH ───────────────
    ("găsește facturile din martie", "search"),
    ("caută contractele cu TechSoft", "search"),
    ("arată documentele din 2024", "search"),
    ("unde scrie despre clauza de reziliere", "search"),
    ("ce scrie în contract despre penalități", "search"),
    ("caută factura numărul 1234", "search"),
    ("găsește toate facturile de la DataPro", "search"),
    ("arată-mi contractele semnate anul trecut", "search"),
    ("există vreun document despre confidențialitate", "search"),
    ("caută în documente termenul de plată", "search"),
    ("vreau să văd facturile peste 5000 lei", "search"),
    ("localizează contractul cu furnizorul ACME", "search"),
    ("ce documente avem despre CloudNet", "search"),
    ("găsește clauzele de garanție", "search"),
    ("caută informații despre livrare în contracte", "search"),
    ("arată facturile neplătite", "search"),
    ("unde găsesc detaliile despre TVA în contract", "search"),
    ("caută mențiuni despre forță majoră", "search"),
    ("ce contracte expiră luna aceasta", "search"),
    ("găsește documentul cu numărul de înregistrare 5678", "search"),
    ("caută după numele furnizorului", "search"),
    ("arată-mi tot ce avem despre proiectul X", "search"),
    ("vreau facturile emise în trimestrul doi", "search"),
    ("găsește contractele de mentenanță", "search"),
    ("caută clauza despre rezilierea anticipată", "search"),
    ("îmi trebuie contractul cu Mega Image", "search"),
    ("vreau să caut prin facturi", "search"),
    ("afișează documentele recente", "search"),
    ("care sunt facturile din ianuarie", "search"),
    ("identifică contractele active", "search"),
    ("găsește unde se menționează garanția", "search"),
    ("arată contractele cu valoare peste 10000", "search"),
    ("caut un document despre asigurare", "search"),
    ("vreau lista facturilor din 2023", "search"),
    ("unde e contractul de prestări servicii", "search"),
    ("caută toate anexele contractului", "search"),
    ("găsește facturile scadente săptămâna asta", "search"),
    ("arată-mi documentele de la furnizorul nou", "search"),
    ("find the invoices from March", "search"),
    ("search for contracts with TechSoft", "search"),
    ("show me the 2024 documents", "search"),
    ("where does it say about the termination clause", "search"),
    ("look up invoice number 1234", "search"),
    ("find all documents about confidentiality", "search"),
    ("search the contracts for payment terms", "search"),
    ("show me unpaid invoices", "search"),
    ("locate the contract with supplier ACME", "search"),
    ("what documents do we have about CloudNet", "search"),
    ("search for the warranty clause", "search"),
    ("find recent contracts", "search"),

    # ─────────────── EXTRACT ───────────────
    ("extrage datele din factură", "extract"),
    ("scoate sumele din contract", "extract"),
    ("parsează PDF-ul atașat", "extract"),
    ("care e totalul facturii", "extract"),
    ("cât e TVA-ul pe factura asta", "extract"),
    ("extrage numărul facturii și data", "extract"),
    ("care e suma de plată", "extract"),
    ("scoate numele furnizorului din document", "extract"),
    ("extrage data scadenței", "extract"),
    ("care e valoarea contractului", "extract"),
    ("extrage toate câmpurile structurate din factură", "extract"),
    ("ce monedă e folosită în factură", "extract"),
    ("scoate codul fiscal al furnizorului", "extract"),
    ("extrage părțile contractante", "extract"),
    ("care e subtotalul fără TVA", "extract"),
    ("extrage durata contractului", "extract"),
    ("ia numărul de înregistrare din document", "extract"),
    ("care sunt datele de contact din factură", "extract"),
    ("extrage IBAN-ul din factură", "extract"),
    ("scoate procentul de penalizare din contract", "extract"),
    ("care e prețul unitar", "extract"),
    ("extrage cantitatea și prețul", "extract"),
    ("parsează tabelul cu produse", "extract"),
    ("care e data emiterii facturii", "extract"),
    ("extrage adresa furnizorului", "extract"),
    ("extrage valoarea totală cu TVA", "extract"),
    ("care e numărul contractului", "extract"),
    ("scoate toate datele din PDF", "extract"),
    ("extrage informațiile de facturare", "extract"),
    ("ce sumă apare pe factură", "extract"),
    ("extrage codul CPV din anunț", "extract"),
    ("care e autoritatea contractantă", "extract"),
    ("scoate valoarea estimată din anunț", "extract"),
    ("extrage câmpurile cheie din contract", "extract"),
    ("ia data și suma din factură", "extract"),
    ("care e termenul de plată în zile", "extract"),
    ("extrage numele clientului și suma", "extract"),
    ("extract the data from the invoice", "extract"),
    ("get the amounts from the contract", "extract"),
    ("parse the attached PDF", "extract"),
    ("what is the invoice total", "extract"),
    ("what's the VAT on this invoice", "extract"),
    ("extract the invoice number and date", "extract"),
    ("what is the amount due", "extract"),
    ("get the supplier name from the document", "extract"),
    ("extract the due date", "extract"),
    ("what is the contract value", "extract"),
    ("extract the IBAN from the invoice", "extract"),
    ("get the tax id of the supplier", "extract"),

    # ─────────────── SUMMARIZE ───────────────
    ("rezumă contractul cu DataPro", "summarize"),
    ("fă-mi un rezumat al facturilor din martie", "summarize"),
    ("pe scurt, ce conține contractul", "summarize"),
    ("sumarizează documentul", "summarize"),
    ("dă-mi un overview al contractelor active", "summarize"),
    ("rezumă clauzele principale", "summarize"),
    ("spune-mi pe scurt despre ce e factura", "summarize"),
    ("fă un sumar al întâlnirii", "summarize"),
    ("rezumă pe scurt termenii contractului", "summarize"),
    ("vreau un rezumat al situației financiare", "summarize"),
    ("sumarizează principalele puncte", "summarize"),
    ("dă-mi esența contractului în câteva fraze", "summarize"),
    ("rezumă toate facturile de la furnizorul X", "summarize"),
    ("fă-mi un rezumat executiv", "summarize"),
    ("pe scurt, care sunt obligațiile noastre", "summarize"),
    ("rezumă raportul lunar", "summarize"),
    ("sumarizează diferențele dintre cele două contracte", "summarize"),
    ("dă-mi un TL;DR al documentului", "summarize"),
    ("rezumă conținutul facturii", "summarize"),
    ("fă o sinteză a contractelor din 2024", "summarize"),
    ("rezumă pe scurt ce trebuie să plătim", "summarize"),
    ("vreau un sumar al clauzelor de penalizare", "summarize"),
    ("rezumă negocierea", "summarize"),
    ("sumarizează în trei puncte contractul", "summarize"),
    ("dă-mi pe scurt concluziile", "summarize"),
    ("rezumă-mi situația plăților", "summarize"),
    ("fă un rezumat scurt al anunțului", "summarize"),
    ("sumarizează datele financiare", "summarize"),
    ("vreau esența pe scurt", "summarize"),
    ("rezumă tot ce s-a discutat", "summarize"),
    ("fă-mi o sinteză a documentului", "summarize"),
    ("rezumă principalele riscuri din contract", "summarize"),
    ("pe scurt despre furnizorul ăsta", "summarize"),
    ("sumarizează raportul de achiziții", "summarize"),
    ("dă-mi un sumar al valorilor contractuale", "summarize"),
    ("rezumă în câteva rânduri", "summarize"),
    ("fă un overview rapid al facturilor", "summarize"),
    ("summarize the contract with DataPro", "summarize"),
    ("give me a summary of the March invoices", "summarize"),
    ("in short, what does the contract contain", "summarize"),
    ("summarize this document", "summarize"),
    ("give me an overview of active contracts", "summarize"),
    ("summarize the main clauses", "summarize"),
    ("tldr of the document", "summarize"),
    ("give me an executive summary", "summarize"),
    ("sum up the key points", "summarize"),
    ("briefly, what are our obligations", "summarize"),
    ("summarize the quarterly report", "summarize"),
    ("sum up what we owe", "summarize"),
]


# Set held-out — formulări noi, nu apar în TRAINING_DATA. Pentru benchmark onest.
TEST_DATA: list[tuple[str, str]] = [
    ("caută contractul de închiriere", "search"),
    ("găsește facturile de la SecureIT", "search"),
    ("arată documentele expirate", "search"),
    ("unde scrie despre rambursare", "search"),
    ("find the lease agreement", "search"),
    ("show invoices over 2000 eur", "search"),
    ("vreau să văd contractele noi", "search"),
    ("caută clauza de neconcurență", "search"),
    ("care e totalul cu tot cu TVA", "extract"),
    ("extrage data și numărul facturii", "extract"),
    ("scoate codul fiscal din contract", "extract"),
    ("what is the net amount", "extract"),
    ("extrage valoarea în EUR", "extract"),
    ("care e IBAN-ul furnizorului", "extract"),
    ("get the contract duration", "extract"),
    ("extrage prețul unitar al produsului", "extract"),
    ("rezumă-mi contractul ăsta", "summarize"),
    ("fă un sumar al facturilor restante", "summarize"),
    ("pe scurt ce obligații avem", "summarize"),
    ("summarize the agreement briefly", "summarize"),
    ("dă-mi un overview al situației", "summarize"),
    ("tldr al raportului", "summarize"),
    ("sumarizează clauzele de plată", "summarize"),
    ("rezumă pe scurt riscurile", "summarize"),
]
